const DOGS = [
  {
    name: "Affenpinscher",
    imageUrl: "https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg",
    weight: "3 - 6",
    height: "23 - 29",
    life_span: "10 - 12 years",
    temperament: [
      "Stubborn",
      "Curious",
      "Playful",
      "Adventurous",
      "Active",
      "Fun-loving",
    ],
    breed_group: "Toy",
  },
  {
    name: "Afghan Hound",
    imageUrl: "https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg",
    weight: "23 - 27",
    height: "64 - 69",
    life_span: "10 - 13 years",
    temperament: ["Aloof", "Clownish", "Dignified", "Independent", "Happy"],
    breed_group: "Hound",
  },
  {
    name: "African Hunting Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/rkiByec47.jpg",
    weight: "20 - 30",
    height: "76",
    life_span: "11 years",
    temperament: ["Wild", "Hardworking", "Dutiful"],
  },
  {
    name: "Airedale Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg",
    weight: "18 - 29",
    height: "53 - 58",
    life_span: "10 - 13 years",
    temperament: [
      "Outgoing",
      "Friendly",
      "Alert",
      "Confident",
      "Intelligent",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Akbash Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg",
    weight: "41 - 54",
    height: "71 - 86",
    life_span: "10 - 12 years",
    temperament: ["Loyal", "Independent", "Intelligent", "Brave"],
    breed_group: "Working",
  },
  {
    name: "Akita",
    imageUrl: "https://cdn2.thedogapi.com/images/BFRYBufpm.jpg",
    weight: "29 - 52",
    height: "61 - 71",
    life_span: "10 - 14 years",
    temperament: [
      "Docile",
      "Alert",
      "Responsive",
      "Dignified",
      "Composed",
      "Friendly",
      "Receptive",
      "Faithful",
      "Courageous",
    ],
    breed_group: "Working",
  },
  {
    name: "Alapaha Blue Blood Bulldog",
    imageUrl: "https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg",
    weight: "25 - 41",
    height: "46 - 61",
    life_span: "12 - 13 years",
    temperament: [
      "Loving",
      "Protective",
      "Trainable",
      "Dutiful",
      "Responsible",
    ],
    breed_group: "Mixed",
  },
  {
    name: "Alaskan Husky",
    imageUrl: "https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg",
    weight: "17 - 23",
    height: "58 - 66",
    life_span: "10 - 13 years",
    temperament: ["Friendly", "Energetic", "Loyal", "Gentle", "Confident"],
    breed_group: "Mixed",
  },
  {
    name: "Alaskan Malamute",
    imageUrl: "https://cdn2.thedogapi.com/images/dW5UucTIW.jpg",
    weight: "29 - 45",
    height: "58 - 64",
    life_span: "12 - 15 years",
    temperament: [
      "Friendly",
      "Affectionate",
      "Devoted",
      "Loyal",
      "Dignified",
      "Playful",
    ],
    breed_group: "Working",
  },
  {
    name: "American Bulldog",
    imageUrl: "https://cdn2.thedogapi.com/images/pk1AAdloG.jpg",
    weight: "27 - 54",
    height: "56 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Friendly",
      "Assertive",
      "Energetic",
      "Loyal",
      "Gentle",
      "Confident",
      "Dominant",
    ],
    breed_group: "Working",
  },
  {
    name: "American Bully",
    imageUrl: "https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg",
    weight: "14 - 68",
    height: "36 - 43",
    life_span: "8 – 15 years",
    temperament: [
      "Strong Willed",
      "Stubborn",
      "Friendly",
      "Clownish",
      "Affectionate",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Courageous",
    ],
  },
  {
    name: "American Eskimo Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/Bymjyec4m.jpg",
    weight: "9 - 18",
    height: "38 - 48",
    life_span: "12 - 15 years",
    temperament: ["Friendly", "Alert", "Reserved", "Intelligent", "Protective"],
    breed_group: "Non-Sporting",
  },
  {
    name: "American Eskimo Dog (Miniature)",
    imageUrl: "https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg",
    weight: "3 - 5",
    height: "23 - 30",
    life_span: "13 – 15 years",
    temperament: ["Friendly", "Alert", "Reserved", "Intelligent", "Protective"],
    breed_group: undefined,
  },
  {
    name: "American Foxhound",
    imageUrl: "https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg",
    weight: "29 - 34",
    height: "53 - 71",
    life_span: "8 - 15 years",
    temperament: [
      "Kind",
      "Sweet-Tempered",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
    ],
    breed_group: "Hound",
  },
  {
    name: "American Pit Bull Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/HkC31gcNm.png",
    weight: "14 - 27",
    height: "43 - 53",
    life_span: "10 - 15 years",
    temperament: [
      "Strong Willed",
      "Stubborn",
      "Friendly",
      "Clownish",
      "Affectionate",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "American Staffordshire Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/rJIakgc4m.jpg",
    weight: "23 - 27",
    height: "43 - 48",
    life_span: "12 - 15 years",
    temperament: [
      "Tenacious",
      "Friendly",
      "Devoted",
      "Loyal",
      "Attentive",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "American Water Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg",
    weight: "11 - 20",
    height: "38 - 46",
    life_span: "10 - 12 years",
    temperament: [
      "Friendly",
      "Energetic",
      "Obedient",
      "Intelligent",
      "Protective",
      "Trainable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Anatolian Shepherd Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg",
    weight: "36 - 68",
    height: "69 - 74",
    life_span: "11 - 13 years",
    temperament: [
      "Steady",
      "Bold",
      "Independent",
      "Confident",
      "Intelligent",
      "Proud",
    ],
    breed_group: "Working",
  },
  {
    name: "Appenzeller Sennenhund",
    imageUrl: "https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg",
    weight: "22 - 25",
    height: "51 - 56",
    life_span: "12 – 14 years",
    temperament: [
      "Reliable",
      "Fearless",
      "Energetic",
      "Lively",
      "Self-assured",
    ],
  },
  {
    name: "Australian Cattle Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg",
    weight: "20 - 28",
    height: "43 - 51",
    life_span: "12 - 14 years",
    temperament: [
      "Cautious",
      "Energetic",
      "Loyal",
      "Obedient",
      "Protective",
      "Brave",
    ],
    breed_group: "Herding",
  },
  {
    name: "Australian Kelpie",
    imageUrl: "https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg",
    weight: "14 - 21",
    height: "43 - 51",
    life_span: "10 - 13 years",
    temperament: [
      "Friendly",
      "Energetic",
      "Alert",
      "Loyal",
      "Intelligent",
      "Eager",
    ],
    breed_group: "Herding",
  },
  {
    name: "Australian Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/B1-llgq4m.jpg",
    weight: "16 - 29",
    height: "46 - 58",
    life_span: "12 - 16 years",
    temperament: [
      "Good-natured",
      "Affectionate",
      "Intelligent",
      "Active",
      "Protective",
    ],
    breed_group: "Herding",
  },
  {
    name: "Australian Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg",
    weight: "6 - 7",
    height: "25 - 28",
    life_span: "15 years",
    temperament: [
      "Spirited",
      "Alert",
      "Loyal",
      "Companionable",
      "Even Tempered",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Azawakh",
    imageUrl: "https://cdn2.thedogapi.com/images/SkvZgx94m.jpg",
    weight: "15 - 25",
    height: "58 - 74",
    life_span: "10 - 13 years",
    temperament: [
      "Aloof",
      "Affectionate",
      "Attentive",
      "Rugged",
      "Fierce",
      "Refined",
    ],
    breed_group: "Hound",
  },
  {
    name: "Barbet",
    imageUrl: "https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg",
    weight: "18 - 29",
    height: "51 - 66",
    life_span: "13 – 15 years",
    temperament: ["Obedient", "Companionable", "Intelligent", "Joyful"],
  },
  {
    name: "Basenji",
    imageUrl: "https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg",
    weight: "10 - 11",
    height: "41 - 43",
    life_span: "10 - 12 years",
    temperament: [
      "Affectionate",
      "Energetic",
      "Alert",
      "Curious",
      "Playful",
      "Intelligent",
    ],
    breed_group: "Hound",
  },
  {
    name: "Basset Bleu de Gascogne",
    imageUrl: "https://cdn2.thedogapi.com/images/BkMQll94X.jpg",
    weight: "16 - 18",
    height: "33 - 38",
    life_span: "10 - 14 years",
    temperament: [
      "Affectionate",
      "Lively",
      "Agile",
      "Curious",
      "Happy",
      "Active",
    ],
    breed_group: "Hound",
  },
  {
    name: "Basset Hound",
    imageUrl: "https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg",
    weight: "23 - 29",
    height: "36",
    life_span: "12 - 15 years",
    temperament: [
      "Tenacious",
      "Friendly",
      "Affectionate",
      "Devoted",
      "Sweet-Tempered",
      "Gentle",
    ],
    breed_group: "Hound",
  },
  {
    name: "Beagle",
    imageUrl: "https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg",
    weight: "9 - 16",
    height: "33 - 38",
    life_span: "13 - 16 years",
    temperament: [
      "Amiable",
      "Even Tempered",
      "Excitable",
      "Determined",
      "Gentle",
      "Intelligent",
    ],
    breed_group: "Hound",
  },
  {
    name: "Bearded Collie",
    imageUrl: "https://cdn2.thedogapi.com/images/A09F4c1qP.jpg",
    weight: "20 - 25",
    height: "51 - 56",
    life_span: "12 - 14 years",
    temperament: [
      "Self-confidence",
      "Hardy",
      "Lively",
      "Alert",
      "Intelligent",
      "Active",
    ],
    breed_group: "Herding",
  },
  {
    name: "Beauceron",
    imageUrl: "https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg",
    weight: "36 - 50",
    height: "61 - 70",
    life_span: "10 - 12 years",
    temperament: ["Fearless", "Friendly", "Intelligent", "Protective", "Calm"],
    breed_group: "Herding",
  },
  {
    name: "Bedlington Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/ByK8gx947.jpg",
    weight: "8 - 10",
    height: "38 - 41",
    life_span: "14 - 16 years",
    temperament: ["Affectionate", "Spirited", "Intelligent", "Good-tempered"],
    breed_group: "Terrier",
  },
  {
    name: "Belgian Malinois",
    imageUrl: "https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg",
    weight: "18 - 36",
    height: "56 - 66",
    life_span: "12 - 14 years",
    temperament: [
      "Watchful",
      "Alert",
      "Stubborn",
      "Friendly",
      "Confident",
      "Hard-working",
      "Active",
      "Protective",
    ],
    breed_group: "Herding",
  },
  {
    name: "Belgian Tervuren",
    imageUrl: "https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg",
    weight: "18 - 29",
    height: "56 - 66",
    life_span: "10 - 12 years",
    temperament: [
      "Energetic",
      "Alert",
      "Loyal",
      "Intelligent",
      "Attentive",
      "Protective",
    ],
    breed_group: "Herding",
  },
  {
    name: "Bernese Mountain Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg",
    weight: "29 - 54",
    height: "58 - 70",
    life_span: "7 - 10 years",
    temperament: ["Affectionate", "Loyal", "Intelligent", "Faithful"],
    breed_group: "Working",
  },
  {
    name: "Bichon Frise",
    imageUrl: "https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg",
    weight: "5 - 8",
    height: "24 - 29",
    life_span: "15 years",
    temperament: [
      "Feisty",
      "Affectionate",
      "Cheerful",
      "Playful",
      "Gentle",
      "Sensitive",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Black and Tan Coonhound",
    imageUrl: "https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg",
    weight: "29 - 45",
    height: "58 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Easygoing",
      "Gentle",
      "Adaptable",
      "Trusting",
      "Even Tempered",
      "Lovable",
    ],
    breed_group: "Hound",
  },
  {
    name: "Bloodhound",
    imageUrl: "https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg",
    weight: "36 - 50",
    height: "58 - 69",
    life_span: "8 - 10 years",
    temperament: ["Stubborn", "Affectionate", "Gentle", "Even Tempered"],
    breed_group: "Hound",
  },
  {
    name: "Bluetick Coonhound",
    imageUrl: "https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg",
    weight: "20 - 36",
    height: "53 - 69",
    life_span: "12 - 14 years",
    temperament: ["Friendly", "Intelligent", "Active"],
    breed_group: "Hound",
  },
  {
    name: "Boerboel",
    imageUrl: "https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg",
    weight: "50 - 91",
    height: "56 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Obedient",
      "Confident",
      "Intelligent",
      "Dominant",
      "Territorial",
    ],
    breed_group: "Working",
  },
  {
    name: "Border Collie",
    imageUrl: "https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg",
    weight: "14 - 20",
    height: "46 - 56",
    life_span: "12 - 16 years",
    temperament: [
      "Tenacious",
      "Keen",
      "Energetic",
      "Responsive",
      "Alert",
      "Intelligent",
    ],
    breed_group: "Herding",
  },
  {
    name: "Border Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/HJOpge9Em.jpg",
    weight: "5 - 7",
    height: "28 - 41",
    life_span: "12 - 14 years",
    temperament: [
      "Fearless",
      "Affectionate",
      "Alert",
      "Obedient",
      "Intelligent",
      "Even Tempered",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Boston Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/rkZRggqVX.jpg",
    weight: "5 - 11",
    height: "41 - 43",
    life_span: "11 - 13 years",
    temperament: ["Friendly", "Lively", "Intelligent"],
    breed_group: "Non-Sporting",
  },
  {
    name: "Bouvier des Flandres",
    imageUrl: "https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg",
    weight: "32 - 50",
    height: "60 - 70",
    life_span: "10 - 15 years",
    temperament: [
      "Protective",
      "Loyal",
      "Gentle",
      "Intelligent",
      "Familial",
      "Rational",
    ],
    breed_group: "Herding",
  },
  {
    name: "Boxer",
    imageUrl: "https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg",
    weight: "23 - 32",
    height: "55 - 64",
    life_span: "8 - 10 years",
    temperament: [
      "Devoted",
      "Fearless",
      "Friendly",
      "Cheerful",
      "Energetic",
      "Loyal",
      "Playful",
      "Confident",
      "Intelligent",
      "Bright",
      "Brave",
      "Calm",
    ],
    breed_group: "Working",
  },
  {
    name: "Boykin Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg",
    weight: "11 - 18",
    height: "36 - 46",
    life_span: "10 - 14 years",
    temperament: [
      "Friendly",
      "Energetic",
      "Companionable",
      "Intelligent",
      "Eager",
      "Trainable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Bracco Italiano",
    imageUrl: "https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg",
    weight: "25 - 40",
    height: "55 - 67",
    life_span: "10 - 12 years",
    temperament: [
      "Stubborn",
      "Affectionate",
      "Loyal",
      "Playful",
      "Companionable",
      "Trainable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Briard",
    imageUrl: "https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg",
    weight: "32 - 41",
    height: "56 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Fearless",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Faithful",
      "Protective",
    ],
    breed_group: "Herding",
  },
  {
    name: "Brittany",
    imageUrl: "https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg",
    weight: "14 - 20",
    height: "44 - 52",
    life_span: "12 - 14 years",
    temperament: [
      "Agile",
      "Adaptable",
      "Quick",
      "Intelligent",
      "Attentive",
      "Happy",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Bull Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/VSraIEQGd.jpg",
    weight: "23 - 32",
    height: "53 - 56",
    life_span: "10 - 12 years",
    temperament: [
      "Trainable",
      "Protective",
      "Sweet-Tempered",
      "Keen",
      "Active",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Bull Terrier (Miniature)",
    imageUrl: "https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg",
    weight: "11 - 15",
    height: "25 - 36",
    life_span: "11 – 14 years",
    temperament: [
      "Trainable",
      "Protective",
      "Sweet-Tempered",
      "Keen",
      "Active",
      "Territorial",
    ],
  },
  {
    name: "Bullmastiff",
    imageUrl: "https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg",
    weight: "45 - 59",
    height: "61 - 69",
    life_span: "8 - 12 years",
    temperament: [
      "Docile",
      "Reliable",
      "Devoted",
      "Alert",
      "Loyal",
      "Reserved",
      "Loving",
      "Protective",
      "Powerful",
      "Calm",
      "Courageous",
    ],
    breed_group: "Working",
  },
  {
    name: "Cairn Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg",
    weight: "6 - 6",
    height: "23 - 25",
    life_span: "14 - 15 years",
    temperament: [
      "Hardy",
      "Fearless",
      "Assertive",
      "Gay",
      "Intelligent",
      "Active",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Cane Corso",
    imageUrl: "https://cdn2.thedogapi.com/images/r15m-lc4m.jpg",
    weight: "40 - 54",
    height: "60 - 70",
    life_span: "10 - 11 years",
    temperament: [
      "Trainable",
      "Reserved",
      "Stable",
      "Quiet",
      "Even Tempered",
      "Calm",
    ],
    breed_group: "Working",
  },
  {
    name: "Cardigan Welsh Corgi",
    imageUrl: "https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg",
    weight: "11 - 17",
    height: "27 - 32",
    life_span: "12 - 14 years",
    temperament: [
      "Affectionate",
      "Devoted",
      "Alert",
      "Companionable",
      "Intelligent",
      "Active",
    ],
    breed_group: "Herding",
  },
  {
    name: "Catahoula Leopard Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/BJcNbec4X.jpg",
    weight: "23 - 43",
    height: "51 - 66",
    life_span: "10 - 12 years",
    temperament: [
      "Energetic",
      "Inquisitive",
      "Independent",
      "Gentle",
      "Intelligent",
      "Loving",
    ],
    breed_group: "Herding",
  },
  {
    name: "Caucasian Shepherd (Ovcharka)",
    imageUrl: "https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg",
    weight: "36 - 45",
    height: "61 - 85",
    life_span: "10 - 12 years",
    temperament: ["Alert", "Quick", "Dominant", "Powerful", "Calm", "Strong"],
    breed_group: "Working",
  },
  {
    name: "Cavalier King Charles Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg",
    weight: "6 - 8",
    height: "30 - 33",
    life_span: "10 - 14 years",
    temperament: [
      "Fearless",
      "Affectionate",
      "Sociable",
      "Patient",
      "Playful",
      "Adaptable",
    ],
    breed_group: "Toy",
  },
  {
    name: "Chesapeake Bay Retriever",
    imageUrl: "https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg",
    weight: "25 - 36",
    height: "53 - 66",
    life_span: "10 - 13 years",
    temperament: [
      "Affectionate",
      "Intelligent",
      "Quiet",
      "Dominant",
      "Happy",
      "Protective",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Chinese Crested",
    imageUrl: "https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg",
    weight: "5 - 6",
    height: "28 - 33",
    life_span: "10 - 14 years",
    temperament: [
      "Affectionate",
      "Sweet-Tempered",
      "Lively",
      "Alert",
      "Playful",
      "Happy",
    ],
    breed_group: "Toy",
  },
  {
    name: "Chinese Shar-Pei",
    imageUrl: "https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg",
    weight: "20 - 27",
    height: "46 - 51",
    life_span: "10 years",
    temperament: [
      "Suspicious",
      "Affectionate",
      "Devoted",
      "Reserved",
      "Independent",
      "Loving",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Chinook",
    imageUrl: "https://cdn2.thedogapi.com/images/Sypubg54Q.jpg",
    weight: "23 - 41",
    height: "56 - 66",
    life_span: "12 - 15 years",
    temperament: ["Friendly", "Alert", "Dignified", "Intelligent", "Calm"],
    breed_group: "Working",
  },
  {
    name: "Chow Chow",
    imageUrl: "https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg",
    weight: "18 - 32",
    height: "43 - 51",
    life_span: "12 - 15 years",
    temperament: ["Aloof", "Loyal", "Independent", "Quiet"],
    breed_group: "Non-Sporting",
  },
  {
    name: "Clumber Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg",
    weight: "25 - 39",
    height: "43 - 51",
    life_span: "10 - 12 years",
    temperament: [
      "Affectionate",
      "Loyal",
      "Dignified",
      "Gentle",
      "Calm",
      "Great-hearted",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Cocker Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/1lFmrzECl.jpg",
    weight: "9 - 14",
    height: "36 - 38",
    life_span: "12 - 15 years",
    temperament: [
      "Trainable",
      "Friendly",
      "Affectionate",
      "Playful",
      "Quiet",
      "Faithful",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Cocker Spaniel (American)",
    imageUrl: "https://cdn2.thedogapi.com/images/HkRcZe547.jpg",
    weight: "9 - 14",
    height: "36 - 38",
    life_span: "12 - 15 years",
    temperament: [
      "Outgoing",
      "Sociable",
      "Trusting",
      "Joyful",
      "Even Tempered",
      "Merry",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Coton de Tulear",
    imageUrl: "https://cdn2.thedogapi.com/images/SyviZlqNm.jpg",
    weight: "4 - 7",
    height: "23 - 28",
    life_span: "13 - 16 years",
    temperament: [
      "Affectionate",
      "Lively",
      "Playful",
      "Intelligent",
      "Trainable",
      "Vocal",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Dalmatian",
    imageUrl: "https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg",
    weight: "23 - 25",
    height: "48 - 58",
    life_span: "10 - 13 years",
    temperament: [
      "Outgoing",
      "Friendly",
      "Energetic",
      "Playful",
      "Sensitive",
      "Intelligent",
      "Active",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Doberman Pinscher",
    imageUrl: "https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg",
    weight: "30 - 40",
    height: "61 - 71",
    life_span: "10 years",
    temperament: [
      "Fearless",
      "Energetic",
      "Alert",
      "Loyal",
      "Obedient",
      "Confident",
      "Intelligent",
    ],
    breed_group: "Working",
  },
  {
    name: "Dogo Argentino",
    imageUrl: "https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg",
    weight: "36 - 45",
    height: "60 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Friendly",
      "Affectionate",
      "Cheerful",
      "Loyal",
      "Tolerant",
      "Protective",
    ],
    breed_group: "Working",
  },
  {
    name: "Dutch Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg",
    weight: "23 - 32",
    height: "56 - 62",
    life_span: "15 years",
    temperament: [
      "Reliable",
      "Affectionate",
      "Alert",
      "Loyal",
      "Obedient",
      "Trainable",
    ],
  },
  {
    name: "English Setter",
    imageUrl: "https://cdn2.thedogapi.com/images/By4A-eqVX.jpg",
    weight: "20 - 36",
    height: "61 - 64",
    life_span: "12 years",
    temperament: [
      "Strong Willed",
      "Mischievous",
      "Affectionate",
      "Energetic",
      "Playful",
      "Companionable",
      "Gentle",
      "Hard-working",
      "Intelligent",
      "Eager",
      "People-Oriented",
    ],
    breed_group: "Sporting",
  },
  {
    name: "English Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg",
    weight: "20 - 30",
    height: "46 - 58",
    life_span: "10 - 13 years",
    temperament: [
      "Kind",
      "Energetic",
      "Independent",
      "Adaptable",
      "Intelligent",
      "Bossy",
    ],
    breed_group: "Working",
  },
  {
    name: "English Springer Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg",
    weight: "16 - 23",
    height: "48 - 51",
    life_span: "12 - 14 years",
    temperament: [
      "Affectionate",
      "Cheerful",
      "Alert",
      "Intelligent",
      "Attentive",
      "Active",
    ],
    breed_group: "Sporting",
  },
  {
    name: "English Toy Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg",
    weight: "4 - 6",
    height: "25",
    life_span: "10 - 12 years",
    temperament: [
      "Affectionate",
      "Reserved",
      "Playful",
      "Gentle",
      "Happy",
      "Loving",
    ],
    breed_group: "Toy",
  },
  {
    name: "English Toy Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg",
    weight: "3 - 4",
    height: "25 - 30",
    life_span: "12 - 13 years",
    temperament: [
      "Stubborn",
      "Alert",
      "Companionable",
      "Intelligent",
      "Cunning",
      "Trainable",
    ],
  },
  {
    name: "Eurasier",
    imageUrl: "https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg",
    weight: "18 - 32",
    height: "52 - 60",
    life_span: "12 - 14 years",
    temperament: [
      "Alert",
      "Reserved",
      "Intelligent",
      "Even Tempered",
      "Watchful",
      "Calm",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Field Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/SkJfGecE7.jpg",
    weight: "16 - 23",
    height: "43 - 46",
    life_span: "11 - 15 years",
    temperament: [
      "Docile",
      "Cautious",
      "Sociable",
      "Sensitive",
      "Adaptable",
      "Familial",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Finnish Lapphund",
    imageUrl: "https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg",
    weight: "15 - 24",
    height: "41 - 53",
    life_span: "12 - 15 years",
    temperament: ["Friendly", "Keen", "Faithful", "Calm", "Courageous"],
    breed_group: "Herding",
  },
  {
    name: "Finnish Spitz",
    imageUrl: "https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg",
    weight: "10 - 13",
    height: "39 - 51",
    life_span: "12 - 15 years",
    temperament: [
      "Playful",
      "Loyal",
      "Independent",
      "Intelligent",
      "Happy",
      "Vocal",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "French Bulldog",
    imageUrl: "https://cdn2.thedogapi.com/images/HyWNfxc47.jpg",
    weight: "13",
    height: "28 - 30",
    life_span: "9 - 11 years",
    temperament: [
      "Playful",
      "Affectionate",
      "Keen",
      "Sociable",
      "Lively",
      "Alert",
      "Easygoing",
      "Patient",
      "Athletic",
      "Bright",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "German Pinscher",
    imageUrl: "https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg",
    weight: "11 - 20",
    height: "43 - 51",
    life_span: "12 - 14 years",
    temperament: [
      "Spirited",
      "Lively",
      "Intelligent",
      "Loving",
      "Even Tempered",
      "Familial",
    ],
    breed_group: "Working",
  },
  {
    name: "German Shepherd Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg",
    weight: "23 - 41",
    height: "56 - 66",
    life_span: "10 - 13 years",
    temperament: [
      "Alert",
      "Loyal",
      "Obedient",
      "Curious",
      "Confident",
      "Intelligent",
      "Watchful",
      "Courageous",
    ],
    breed_group: "Herding",
  },
  {
    name: "German Shorthaired Pointer",
    imageUrl: "https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg",
    weight: "20 - 32",
    height: "53 - 64",
    life_span: "12 - 14 years",
    temperament: [
      "Boisterous",
      "Bold",
      "Affectionate",
      "Intelligent",
      "Cooperative",
      "Trainable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Giant Schnauzer",
    imageUrl: "https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg",
    weight: "29 - 41",
    height: "60 - 70",
    life_span: "10 - 12 years",
    temperament: [
      "Strong Willed",
      "Kind",
      "Loyal",
      "Intelligent",
      "Dominant",
      "Powerful",
    ],
    breed_group: "Working",
  },
  {
    name: "Glen of Imaal Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/H1oLMe94m.jpg",
    weight: "15 - 18",
    height: "32 - 36",
    life_span: "12 - 15 years",
    temperament: [
      "Spirited",
      "Agile",
      "Loyal",
      "Gentle",
      "Active",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Golden Retriever",
    imageUrl: "https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg",
    weight: "25 - 34",
    height: "55 - 61",
    life_span: "10 - 12 years",
    temperament: [
      "Intelligent",
      "Kind",
      "Reliable",
      "Friendly",
      "Trustworthy",
      "Confident",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Gordon Setter",
    imageUrl: "https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg",
    weight: "20 - 36",
    height: "58 - 69",
    life_span: "10 - 12 years",
    temperament: ["Fearless", "Alert", "Loyal", "Confident", "Gay", "Eager"],
    breed_group: "Sporting",
  },
  {
    name: "Great Dane",
    imageUrl: "https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg",
    weight: "50 - 86",
    height: "71 - 81",
    life_span: "7 - 10 years",
    temperament: [
      "Friendly",
      "Devoted",
      "Reserved",
      "Gentle",
      "Confident",
      "Loving",
    ],
    breed_group: "Working",
  },
  {
    name: "Great Pyrenees",
    imageUrl: "https://cdn2.thedogapi.com/images/B12uzg9V7.png",
    weight: "39 - 52",
    height: "64 - 81",
    life_span: "10 - 12 years",
    temperament: [
      "Strong Willed",
      "Fearless",
      "Affectionate",
      "Patient",
      "Gentle",
      "Confident",
    ],
    breed_group: "Working",
  },
  {
    name: "Greyhound",
    imageUrl: "https://cdn2.thedogapi.com/images/ryNYMx94X.jpg",
    weight: "23 - 32",
    height: "69 - 76",
    life_span: "10 - 13 years",
    temperament: [
      "Affectionate",
      "Athletic",
      "Gentle",
      "Intelligent",
      "Quiet",
      "Even Tempered",
    ],
    breed_group: "Hound",
  },
  {
    name: "Griffon Bruxellois",
    imageUrl: "https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg",
    weight: "5",
    height: "23 - 28",
    life_span: "10 – 15 years",
    temperament: [
      "Self-important",
      "Inquisitive",
      "Alert",
      "Companionable",
      "Sensitive",
      "Watchful",
    ],
  },
  {
    name: "Harrier",
    imageUrl: "https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg",
    weight: "18 - 27",
    height: "46 - 56",
    life_span: "12 - 15 years",
    temperament: [
      "Outgoing",
      "Friendly",
      "Cheerful",
      "Sweet-Tempered",
      "Tolerant",
      "Active",
    ],
    breed_group: "Hound",
  },
  {
    name: "Havanese",
    imageUrl: "https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg",
    weight: "3 - 6",
    height: "22 - 29",
    life_span: "14 - 15 years",
    temperament: [
      "Affectionate",
      "Responsive",
      "Playful",
      "Companionable",
      "Gentle",
      "Intelligent",
    ],
    breed_group: "Toy",
  },
  {
    name: "Irish Setter",
    imageUrl: "https://cdn2.thedogapi.com/images/S1osGeqVm.jpg",
    weight: "16 - 32",
    height: "61 - 69",
    life_span: "10 - 11 years",
    temperament: [
      "Affectionate",
      "Energetic",
      "Lively",
      "Independent",
      "Playful",
      "Companionable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Irish Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/By-hGecVX.jpg",
    weight: "11 - 12",
    height: "46",
    life_span: "12 - 16 years",
    temperament: [
      "Respectful",
      "Lively",
      "Intelligent",
      "Dominant",
      "Protective",
      "Trainable",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Irish Wolfhound",
    imageUrl: "https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg",
    weight: "48 - 82",
    height: "76 - 89",
    life_span: "6 - 8 years",
    temperament: [
      "Sweet-Tempered",
      "Loyal",
      "Dignified",
      "Patient",
      "Thoughtful",
      "Generous",
    ],
    breed_group: "Hound",
  },
  {
    name: "Italian Greyhound",
    imageUrl: "https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg",
    weight: "3 - 7",
    height: "33 - 38",
    life_span: "12 - 15 years",
    temperament: [
      "Mischievous",
      "Affectionate",
      "Agile",
      "Athletic",
      "Companionable",
      "Intelligent",
    ],
    breed_group: "Toy",
  },
  {
    name: "Japanese Chin",
    imageUrl: "https://cdn2.thedogapi.com/images/r1H6feqEm.jpg",
    weight: "2 - 4",
    height: "20 - 28",
    life_span: "12 - 14 years",
    temperament: [
      "Alert",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
      "Cat-like",
    ],
    breed_group: "Toy",
  },
  {
    name: "Japanese Spitz",
    imageUrl: "https://cdn2.thedogapi.com/images/HksaMxqNX.jpg",
    weight: "7 - 9",
    height: "30 - 38",
    life_span: "10 – 16 years",
    temperament: [
      "Affectionate",
      "Obedient",
      "Playful",
      "Companionable",
      "Intelligent",
      "Proud",
    ],
  },
  {
    name: "Keeshond",
    imageUrl: "https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg",
    weight: "16 - 20",
    height: "43 - 46",
    life_span: "12 - 15 years",
    temperament: ["Agile", "Obedient", "Playful", "Quick", "Sturdy", "Bright"],
    breed_group: "Non-Sporting",
  },
  {
    name: "Komondor",
    imageUrl: "https://cdn2.thedogapi.com/images/Bko0fl547.jpg",
    weight: "36 - 45",
    height: "65 - 70",
    life_span: "10 - 12 years",
    temperament: [
      "Steady",
      "Fearless",
      "Affectionate",
      "Independent",
      "Gentle",
      "Calm",
    ],
    breed_group: "Working",
  },
  {
    name: "Kooikerhondje",
    imageUrl: "https://cdn2.thedogapi.com/images/kOMy84GQE.jpg",
    weight: "9 - 14",
    height: "36 - 41",
    life_span: "12 - 15 years",
    temperament: [
      "Benevolent",
      "Agile",
      "Alert",
      "Intelligent",
      "Active",
      "Territorial",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Kuvasz",
    imageUrl: "https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg",
    weight: "32 - 52",
    height: "66 - 76",
    life_span: "8 - 10 years",
    temperament: [
      "Clownish",
      "Loyal",
      "Patient",
      "Independent",
      "Intelligent",
      "Protective",
    ],
    breed_group: "Working",
  },
  {
    name: "Labrador Retriever",
    imageUrl: "https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg",
    weight: "25 - 36",
    height: "55 - 62",
    life_span: "10 - 13 years",
    temperament: [
      "Kind",
      "Outgoing",
      "Agile",
      "Gentle",
      "Intelligent",
      "Trusting",
      "Even Tempered",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Lagotto Romagnolo",
    imageUrl: "https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg",
    weight: "11 - 16",
    height: "41 - 48",
    life_span: "14 - 16 years",
    temperament: [
      "Keen",
      "Loyal",
      "Companionable",
      "Loving",
      "Active",
      "Trainable",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Lancashire Heeler",
    imageUrl: "https://cdn2.thedogapi.com/images/S1RGml5Em.jpg",
    weight: "3 - 6",
    height: "25 - 30",
    life_span: "12 – 15 years",
    temperament: ["Clever", "Friendly", "Alert", "Intelligent"],
  },
  {
    name: "Leonberger",
    imageUrl: "https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg",
    weight: "54 - 77",
    height: "65 - 80",
    life_span: "6 - 8 years",
    temperament: [
      "Obedient",
      "Fearless",
      "Loyal",
      "Companionable",
      "Adaptable",
      "Loving",
    ],
    breed_group: "Working",
  },
  {
    name: "Lhasa Apso",
    imageUrl: "https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg",
    weight: "5 - 8",
    height: "25 - 28",
    life_span: "12 - 15 years",
    temperament: [
      "Steady",
      "Fearless",
      "Friendly",
      "Devoted",
      "Assertive",
      "Spirited",
      "Energetic",
      "Lively",
      "Alert",
      "Obedient",
      "Playful",
      "Intelligent",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Maltese",
    imageUrl: "https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg",
    weight: "2 - 3",
    height: "20 - 25",
    life_span: "15 - 18 years",
    temperament: [
      "Playful",
      "Docile",
      "Fearless",
      "Affectionate",
      "Sweet-Tempered",
      "Lively",
      "Responsive",
      "Easygoing",
      "Gentle",
      "Intelligent",
      "Active",
    ],
    breed_group: "Toy",
  },
  {
    name: "Miniature American Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg",
    weight: "9 - 18",
    height: "33 - 46",
    life_span: "12 - 15 years",
    temperament: ["Energetic", "Loyal", "Intelligent", "Trainable"],
    breed_group: "Herding",
  },
  {
    name: "Miniature Pinscher",
    imageUrl: "https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg",
    weight: "4 - 5",
    height: "25 - 32",
    life_span: "15 years",
    temperament: [
      "Clever",
      "Outgoing",
      "Friendly",
      "Energetic",
      "Responsive",
      "Playful",
    ],
    breed_group: "Toy",
  },
  {
    name: "Miniature Schnauzer",
    imageUrl: "https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg",
    weight: "5 - 9",
    height: "30 - 36",
    life_span: "12 - 14 years",
    temperament: [
      "Fearless",
      "Friendly",
      "Spirited",
      "Alert",
      "Obedient",
      "Intelligent",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Newfoundland",
    imageUrl: "https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg",
    weight: "45 - 68",
    height: "66 - 71",
    life_span: "8 - 10 years",
    temperament: ["Sweet-Tempered", "Gentle", "Trainable"],
    breed_group: "Working",
  },
  {
    name: "Norfolk Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/B1ADQg94X.jpg",
    weight: "5 - 5",
    height: "23 - 25",
    life_span: "12 - 15 years",
    temperament: [
      "Self-confidence",
      "Fearless",
      "Spirited",
      "Companionable",
      "Happy",
      "Lovable",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Norwich Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg",
    weight: "5 - 5",
    height: "25",
    life_span: "12 - 15 years",
    temperament: [
      "Hardy",
      "Affectionate",
      "Energetic",
      "Sensitive",
      "Intelligent",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Nova Scotia Duck Tolling Retriever",
    imageUrl: "https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg",
    weight: "16 - 23",
    height: "43 - 53",
    life_span: "12 - 14 years",
    temperament: ["Outgoing", "Alert", "Patient", "Intelligent", "Loving"],
    breed_group: "Sporting",
  },
  {
    name: "Old English Sheepdog",
    imageUrl: "https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg",
    weight: "27 - 45",
    height: "53",
    life_span: "10 - 12 years",
    temperament: [
      "Sociable",
      "Bubbly",
      "Playful",
      "Adaptable",
      "Intelligent",
      "Loving",
    ],
    breed_group: "Herding",
  },
  {
    name: "Olde English Bulldogge",
    imageUrl: "https://cdn2.thedogapi.com/images/B1d5me547.jpg",
    weight: "NaN",
    height: "38 - 48",
    life_span: "9 – 14 years",
    temperament: [
      "Friendly",
      "Alert",
      "Confident",
      "Loving",
      "Courageous",
      "Strong",
    ],
  },
  {
    name: "Papillon",
    imageUrl: "https://cdn2.thedogapi.com/images/SkJj7e547.jpg",
    weight: "1 - 5",
    height: "20 - 28",
    life_span: "13 - 17 years",
    temperament: [
      "Hardy",
      "Friendly",
      "Energetic",
      "Alert",
      "Intelligent",
      "Happy",
    ],
    breed_group: "Toy",
  },
  {
    name: "Pekingese",
    imageUrl: "https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg",
    weight: "6",
    height: "15 - 23",
    life_span: "14 - 18 years",
    temperament: [
      "Opinionated",
      "Good-natured",
      "Stubborn",
      "Affectionate",
      "Aggressive",
      "Intelligent",
    ],
    breed_group: "Toy",
  },
  {
    name: "Pembroke Welsh Corgi",
    imageUrl: "https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg",
    weight: "11 - 14",
    height: "25 - 30",
    life_span: "12 - 14 years",
    temperament: [
      "Tenacious",
      "Outgoing",
      "Friendly",
      "Bold",
      "Playful",
      "Protective",
    ],
    breed_group: "Herding",
  },
  {
    name: "Perro de Presa Canario",
    imageUrl: "https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg",
    weight: "40 - 50",
    height: "56 - 65",
    life_span: "10 - 12 years",
    temperament: ["Strong Willed", "Suspicious", "Gentle", "Dominant", "Calm"],
    breed_group: "Working",
  },
  {
    name: "Pharaoh Hound",
    imageUrl: "https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg",
    weight: "18 - 27",
    height: "53 - 64",
    life_span: "12 - 14 years",
    temperament: [
      "Affectionate",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
      "Trainable",
    ],
    breed_group: "Hound",
  },
  {
    name: "Plott",
    imageUrl: "https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg",
    weight: "18 - 27",
    height: "51 - 64",
    life_span: "12 - 14 years",
    temperament: ["Bold", "Alert", "Loyal", "Intelligent"],
    breed_group: "Hound",
  },
  {
    name: "Pomeranian",
    imageUrl: "https://cdn2.thedogapi.com/images/HJd0XecNX.jpg",
    weight: "1 - 3",
    height: "20 - 30",
    life_span: "15 years",
    temperament: [
      "Extroverted",
      "Friendly",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
    ],
    breed_group: "Toy",
  },
  {
    name: "Poodle (Miniature)",
    imageUrl: "https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg",
    weight: "7 - 8",
    height: "28 - 38",
    life_span: "12 – 15 years",
    temperament: [
      "Extroverted",
      "Friendly",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
    ],
  },
  {
    name: "Poodle (Toy)",
    imageUrl: "https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg",
    weight: "3 - 4",
    height: "23 - 28",
    life_span: "18 years",
    temperament: [
      "Extroverted",
      "Friendly",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
    ],
  },
  {
    name: "Pug",
    imageUrl: "https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg",
    weight: "6 - 8",
    height: "25 - 30",
    life_span: "12 - 14 years",
    temperament: [
      "Docile",
      "Clever",
      "Charming",
      "Stubborn",
      "Sociable",
      "Playful",
      "Quiet",
      "Attentive",
    ],
    breed_group: "Toy",
  },
  {
    name: "Puli",
    imageUrl: "https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg",
    weight: "11 - 16",
    height: "41 - 43",
    life_span: "12 - 16 Years years",
    temperament: [
      "Energetic",
      "Agile",
      "Loyal",
      "Obedient",
      "Intelligent",
      "Faithful",
    ],
    breed_group: "Herding",
  },
  {
    name: "Pumi",
    imageUrl: "https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg",
    weight: "8 - 15",
    height: "38 - 47",
    life_span: "13 - 15 years",
    temperament: [
      "Lively",
      "Reserved",
      "Intelligent",
      "Active",
      "Protective",
      "Vocal",
    ],
    breed_group: "Herding",
  },
  {
    name: "Rat Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg",
    weight: "4 - 11",
    height: "25 - 33",
    life_span: "12 - 18 years",
    temperament: [
      "Affectionate",
      "Lively",
      "Inquisitive",
      "Alert",
      "Intelligent",
      "Loving",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Redbone Coonhound",
    imageUrl: "https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg",
    weight: "20 - 36",
    height: "53 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Affectionate",
      "Energetic",
      "Independent",
      "Companionable",
      "Familial",
      "Unflappable",
    ],
    breed_group: "Hound",
  },
  {
    name: "Rhodesian Ridgeback",
    imageUrl: "https://cdn2.thedogapi.com/images/By9zNgqE7.jpg",
    weight: "34 - 36",
    height: "61 - 69",
    life_span: "10 - 12 years",
    temperament: [
      "Strong Willed",
      "Mischievous",
      "Loyal",
      "Dignified",
      "Sensitive",
      "Intelligent",
    ],
    breed_group: "Hound",
  },
  {
    name: "Rottweiler",
    imageUrl: "https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg",
    weight: "34 - 50",
    height: "56 - 69",
    life_span: "8 - 10 years",
    temperament: [
      "Steady",
      "Good-natured",
      "Fearless",
      "Devoted",
      "Alert",
      "Obedient",
      "Confident",
      "Self-assured",
      "Calm",
      "Courageous",
    ],
    breed_group: "Working",
  },
  {
    name: "Russian Toy",
    imageUrl: "https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg",
    weight: "1 - 3",
    height: "19 - 27",
    life_span: "10 - 12 years",
    temperament: [
      "Extroverted",
      "Friendly",
      "Sociable",
      "Playful",
      "Intelligent",
      "Active",
    ],
    breed_group: "Toy",
  },
  {
    name: "Saint Bernard",
    imageUrl: "https://cdn2.thedogapi.com/images/_Qf9nfRzL.png",
    weight: "59 - 82",
    height: "65 - 70",
    life_span: "7 - 10 years",
    temperament: ["Friendly", "Lively", "Gentle", "Watchful", "Calm"],
    breed_group: "Working",
  },
  {
    name: "Saluki",
    imageUrl: "https://cdn2.thedogapi.com/images/fjFIuehNo.jpg",
    weight: "16 - 29",
    height: "58 - 71",
    life_span: "12 - 14 years",
    temperament: ["Aloof", "Reserved", "Intelligent", "Quiet"],
    breed_group: "Hound",
  },
  {
    name: "Samoyed",
    imageUrl: "https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg",
    weight: "23 - 27",
    height: "48 - 60",
    life_span: "12 - 14 years",
    temperament: [
      "Stubborn",
      "Friendly",
      "Sociable",
      "Lively",
      "Alert",
      "Playful",
    ],
    breed_group: "Working",
  },
  {
    name: "Schipperke",
    imageUrl: "https://cdn2.thedogapi.com/images/SyBvVgc47.jpg",
    weight: "5 - 7",
    height: "25 - 33",
    life_span: "13 - 15 years",
    temperament: [
      "Fearless",
      "Agile",
      "Curious",
      "Independent",
      "Confident",
      "Faithful",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Scottish Deerhound",
    imageUrl: "https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg",
    weight: "32 - 59",
    height: "71 - 81",
    life_span: "8 - 10 years",
    temperament: ["Docile", "Friendly", "Dignified", "Gentle"],
    breed_group: "Hound",
  },
  {
    name: "Scottish Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/Bklnce5NX.jpg",
    weight: "8 - 10",
    height: "25",
    life_span: "11 - 13 years",
    temperament: [
      "Feisty",
      "Alert",
      "Independent",
      "Playful",
      "Quick",
      "Self-assured",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Shetland Sheepdog",
    imageUrl: "https://cdn2.thedogapi.com/images/rJa29l9E7.jpg",
    weight: "14",
    height: "33 - 41",
    life_span: "12 - 14 years",
    temperament: [
      "Affectionate",
      "Lively",
      "Responsive",
      "Alert",
      "Loyal",
      "Reserved",
      "Playful",
      "Gentle",
      "Intelligent",
      "Active",
      "Trainable",
      "Strong",
    ],
    breed_group: "Herding",
  },
  {
    name: "Shiba Inu",
    imageUrl: "https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg",
    weight: "8 - 10",
    height: "34 - 42",
    life_span: "12 - 16 years",
    temperament: [
      "Charming",
      "Fearless",
      "Keen",
      "Alert",
      "Confident",
      "Faithful",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Shih Tzu",
    imageUrl: "https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg",
    weight: "4 - 7",
    height: "20 - 28",
    life_span: "10 - 18 years",
    temperament: [
      "Clever",
      "Spunky",
      "Outgoing",
      "Friendly",
      "Affectionate",
      "Lively",
      "Alert",
      "Loyal",
      "Independent",
      "Playful",
      "Gentle",
      "Intelligent",
      "Happy",
      "Active",
      "Courageous",
    ],
    breed_group: "Toy",
  },
  {
    name: "Shiloh Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/SJJxjecEX.jpg",
    weight: "54 - 64",
    height: "66 - 76",
    life_span: "9 – 14 years",
    temperament: [
      "Outgoing",
      "Loyal",
      "Companionable",
      "Gentle",
      "Loving",
      "Trainable",
    ],
  },
  {
    name: "Siberian Husky",
    imageUrl: "https://cdn2.thedogapi.com/images/S17ZilqNm.jpg",
    weight: "16 - 27",
    height: "51 - 60",
    life_span: "12 years",
    temperament: ["Outgoing", "Friendly", "Alert", "Gentle", "Intelligent"],
    breed_group: "Working",
  },
  {
    name: "Silky Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg",
    weight: "4 - 5",
    height: "23 - 25",
    life_span: "12 - 15 years",
    temperament: [
      "Friendly",
      "Responsive",
      "Inquisitive",
      "Alert",
      "Quick",
      "Joyful",
    ],
    breed_group: "Toy",
  },
  {
    name: "Smooth Fox Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/Syszjx9Em.jpg",
    weight: "NaN - 8",
    height: "39",
    life_span: "12 - 14 years",
    temperament: [
      "Fearless",
      "Affectionate",
      "Alert",
      "Playful",
      "Intelligent",
      "Active",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Soft Coated Wheaten Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg",
    weight: "14 - 18",
    height: "41 - 46",
    life_span: "12 - 15 years",
    temperament: [
      "Affectionate",
      "Spirited",
      "Energetic",
      "Playful",
      "Intelligent",
      "Faithful",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Spanish Water Dog",
    imageUrl: "https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg",
    weight: "14 - 23",
    height: "41 - 51",
    life_span: "12 - 15 years",
    temperament: [
      "Trainable",
      "Diligent",
      "Affectionate",
      "Loyal",
      "Athletic",
      "Intelligent",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Spinone Italiano",
    imageUrl: "https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg",
    weight: "28 - 39",
    height: "57 - 70",
    life_span: "10 - 12 years",
    temperament: [
      "Docile",
      "Friendly",
      "Affectionate",
      "Loyal",
      "Patient",
      "Gentle",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Staffordshire Bull Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/H1zSie9V7.jpg",
    weight: "11 - 17",
    height: "36 - 41",
    life_span: "12 - 14 years",
    temperament: [
      "Reliable",
      "Fearless",
      "Bold",
      "Affectionate",
      "Loyal",
      "Intelligent",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Standard Schnauzer",
    imageUrl: "https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg",
    weight: "14 - 23",
    height: "44 - 50",
    life_span: "13 - 15 years",
    temperament: [
      "Trainable",
      "Good-natured",
      "Devoted",
      "Lively",
      "Playful",
      "Intelligent",
    ],
    breed_group: "Working",
  },
  {
    name: "Swedish Vallhund",
    imageUrl: "https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg",
    weight: "9 - 14",
    height: "29 - 34",
    life_span: "12 - 14 years",
    temperament: [
      "Fearless",
      "Friendly",
      "Energetic",
      "Alert",
      "Intelligent",
      "Watchful",
    ],
    breed_group: "Herding",
  },
  {
    name: "Thai Ridgeback",
    imageUrl: "https://cdn2.thedogapi.com/images/zv89hR-O8.jpg",
    weight: "16 - 25",
    height: "51 - 61",
    life_span: "10 - 12 years",
    temperament: [
      "Protective",
      "Loyal",
      "Independent",
      "Intelligent",
      "Loving",
      "Familial",
    ],
    breed_group: "Hound",
  },
  {
    name: "Tibetan Mastiff",
    imageUrl: "https://cdn2.thedogapi.com/images/SkM9sec47.jpg",
    weight: "39 - 64",
    height: "61 - 66",
    life_span: "10 - 14 years",
    temperament: [
      "Strong Willed",
      "Tenacious",
      "Aloof",
      "Stubborn",
      "Intelligent",
      "Protective",
    ],
    breed_group: "Working",
  },
  {
    name: "Tibetan Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/Hyjcol947.jpg",
    weight: "4 - 7",
    height: "25",
    life_span: "12 - 15 years",
    temperament: [
      "Willful",
      "Aloof",
      "Assertive",
      "Independent",
      "Playful",
      "Intelligent",
      "Happy",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Tibetan Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/6f5n_42mB.jpg",
    weight: "9 - 11",
    height: "36 - 43",
    life_span: "12 - 15 years",
    temperament: [
      "Affectionate",
      "Energetic",
      "Amiable",
      "Reserved",
      "Gentle",
      "Sensitive",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Toy Fox Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/B17ase9V7.jpg",
    weight: "2 - 4",
    height: "20 - 28",
    life_span: "12 - 15 years",
    temperament: [
      "Friendly",
      "Spirited",
      "Alert",
      "Loyal",
      "Playful",
      "Intelligent",
    ],
    breed_group: "Toy",
  },
  {
    name: "Treeing Walker Coonhound",
    imageUrl: "https://cdn2.thedogapi.com/images/SkRpsgc47.jpg",
    weight: "20 - 36",
    height: "51 - 69",
    life_span: "10 - 13 years",
    temperament: [
      "Clever",
      "Affectionate",
      "Confident",
      "Intelligent",
      "Loving",
      "Trainable",
    ],
    breed_group: "Hound",
  },
  {
    name: "Vizsla",
    imageUrl: "https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg",
    weight: "23 - 29",
    height: "53 - 61",
    life_span: "10 - 14 years",
    temperament: ["Affectionate", "Energetic", "Loyal", "Gentle", "Quiet"],
    breed_group: "Sporting",
  },
  {
    name: "Weimaraner",
    imageUrl: "https://cdn2.thedogapi.com/images/SyU12l9V7.jpg",
    weight: "25 - 41",
    height: "58 - 69",
    life_span: "12 - 15 years",
    temperament: [
      "Steady",
      "Aloof",
      "Stubborn",
      "Energetic",
      "Alert",
      "Intelligent",
      "Powerful",
      "Fast",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Welsh Springer Spaniel",
    imageUrl: "https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg",
    weight: "16 - 25",
    height: "43 - 48",
    life_span: "12 - 15 years",
    temperament: [
      "Stubborn",
      "Friendly",
      "Affectionate",
      "Loyal",
      "Playful",
      "Active",
    ],
    breed_group: "Sporting",
  },
  {
    name: "West Highland White Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg",
    weight: "7 - 10",
    height: "25 - 28",
    life_span: "15 - 20 years",
    temperament: [
      "Hardy",
      "Friendly",
      "Alert",
      "Independent",
      "Gay",
      "Active",
      "Courageous",
    ],
    breed_group: "Terrier",
  },
  {
    name: "Whippet",
    imageUrl: "https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg",
    weight: "11 - 16",
    height: "46 - 56",
    life_span: "12 - 15 years",
    temperament: [
      "Friendly",
      "Affectionate",
      "Lively",
      "Gentle",
      "Intelligent",
      "Quiet",
    ],
    breed_group: "Hound",
  },
  {
    name: "White Shepherd",
    imageUrl: "https://cdn2.thedogapi.com/images/r14M3e9E7.jpg",
    weight: "27 - 39",
    height: "56 - 64",
    life_span: "12 – 14 years",
    temperament: [
      "Self-confidence",
      "Aloof",
      "Fearless",
      "Alert",
      "Companionable",
      "Eager",
    ],
  },
  {
    name: "Wire Fox Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg",
    weight: "7 - 9",
    height: "33 - 41",
    life_span: "13 – 14 years",
    temperament: ["Fearless", "Friendly", "Bold", "Keen", "Alert", "Quick"],
  },
  {
    name: "Wirehaired Pointing Griffon",
    imageUrl: "https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg",
    weight: "20 - 32",
    height: "51 - 61",
    life_span: "12 - 14 years",
    temperament: ["Loyal", "Gentle", "Vigilant", "Trainable", "Proud"],
    breed_group: "Sporting",
  },
  {
    name: "Wirehaired Vizsla",
    imageUrl: "https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg",
    weight: "20 - 29",
    height: "55 - 64",
    life_span: "12 - 14 years",
    temperament: [
      "Bold",
      "Independent",
      "Confident",
      "Intelligent",
      "Courageous",
    ],
    breed_group: "Sporting",
  },
  {
    name: "Xoloitzcuintli",
    imageUrl: "https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg",
    weight: "4 - 14",
    height: "25 - 58",
    life_span: "12 - 14 years",
    temperament: [
      "Cheerful",
      "Alert",
      "Companionable",
      "Intelligent",
      "Protective",
      "Calm",
    ],
    breed_group: "Non-Sporting",
  },
  {
    name: "Yorkshire Terrier",
    imageUrl: "https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg",
    weight: "2 - 3",
    height: "20 - 23",
    life_span: "12 - 16 years",
    temperament: [
      "Bold",
      "Independent",
      "Confident",
      "Intelligent",
      "Courageous",
    ],
    breed_group: "Toy",
  },
];

module.exports = {
  DOGS,
};
